services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend-jobhive
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/backend-jobhive
    networks:
      - jobhive-network
    restart: always
  
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend-jobhive
    ports:
      - "5000:5000"
    environment:
      - PORT=5000 
    volumes:
      - ./front-end:/frontend-jobhive
    networks:
      - jobhive-network
    depends_on:
      - backend
    restart: always


networks:
  jobhive-network:
    driver: bridge