name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (front-end)
        run: |
          cd front-end
          pnpm install
          cd ..

      - name: Install dependencies (back-end)
        run: |
          cd back-end
          pnpm install
          cd ..

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
          registry: ghcr.io

      - name: Build and Push Frontend Image
        run: |
          docker build -t ghcr.io/mohammedelghanam/jobhive-frontend:latest ./front-end
          docker push ghcr.io/mohammedelghanam/jobhive-frontend:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t ghcr.io/mohammedelghanam/jobhive-backend:latest ./back-end
          docker push ghcr.io/mohammedelghanam/jobhive-backend:latest