name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (front-end)
        run: |
          cd front-end
          pnpm install
          cd ..

      - name: Install dependencies (back-end)
        run: |
          cd back-end
          pnpm install
          cd ..

      - name: Build Docker Image for Frontend
        run: |
          docker build -t ghcr.io/mohammed_elghanam_jobhive/frontend-jobhive:latest ./front-end

      - name: Build Docker Image for Backend
        run: |
          docker build -t ghcr.io/mohammed_elghanam_jobhive/backend-jobhive:latest ./back-end

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
          registry: ghcr.io

      - name: Push Docker Image for Frontend to GHCR
        run: |
          docker push ghcr.io/mohammedelghanam/mohammed_elghanam_jobhive/frontend-jobhive:latest

      - name: Push Docker Image for Backend to GHCR
        run: |
          docker push ghcr.io/mohammedelghanam/mohammed_elghanam_jobhive/backend-jobhive:latest